# -----------------------------
# This is for grooming
# Note: for indentation use space (never tab!): 2 space indents
# coments start with #
# -----------------------------

metadata: metadata_toy3

# when generic,  names of the sheets in xlsx file that exist (null otherwise) 
abundances : null
mean_enrichment : null
isotopologue_proportions : null
isotopologues : isotopologuesCorrValues  # isotopologue absolute values

groom_out_path : ~/groomexamples/toyp3/raw/   # absolute path


